// ======= EXERCISE DATABASE =======
// Local exercise database — no API needed, works offline

export const exerciseDatabase = [
    // CHEST
    { name: "Barbell Bench Press", muscle: "chest", difficulty: "intermediate", instructions: "Lie flat on a bench, grip the bar slightly wider than shoulder width. Lower the bar to your chest with control, then press back up to full arm extension. Keep your feet flat on the floor and your back naturally arched." },
    { name: "Dumbbell Bench Press", muscle: "chest", difficulty: "beginner", instructions: "Lie on a flat bench holding dumbbells at chest level with palms facing forward. Press the dumbbells up until arms are fully extended, then lower slowly back to the starting position." },
    { name: "Incline Barbell Bench Press", muscle: "chest", difficulty: "intermediate", instructions: "Set bench to 30-45 degrees. Grip the bar wider than shoulder width, lower it to your upper chest, then press back up. Targets the upper chest." },
    { name: "Incline Dumbbell Press", muscle: "chest", difficulty: "beginner", instructions: "Set bench to 30-45 degrees. Hold dumbbells at shoulder level and press upward until arms are extended. Lower slowly and repeat." },
    { name: "Decline Bench Press", muscle: "chest", difficulty: "intermediate", instructions: "Set bench to a decline angle. Lower the bar to your lower chest with control, then press back up. Targets the lower chest." },
    { name: "Cable Fly", muscle: "chest", difficulty: "beginner", instructions: "Stand between two cable machines set at shoulder height. With a slight bend in your elbows, bring your hands together in front of your chest in an arc motion. Slowly return to the starting position." },
    { name: "Dumbbell Fly", muscle: "chest", difficulty: "beginner", instructions: "Lie on a flat bench holding dumbbells above your chest. Lower them out to the sides in a wide arc until you feel a stretch in your chest, then bring them back together." },
    { name: "Push Up", muscle: "chest", difficulty: "beginner", instructions: "Start in a plank position with hands slightly wider than shoulder width. Lower your chest to the floor, then push back up. Keep your body in a straight line throughout." },
    { name: "Chest Dip", muscle: "chest", difficulty: "intermediate", instructions: "Grip parallel bars and lean forward slightly. Lower your body by bending your elbows until you feel a stretch in your chest, then push back up." },

    // BACK
    { name: "Deadlift", muscle: "lower back", difficulty: "intermediate", instructions: "Stand with feet hip-width apart, bar over mid-foot. Hinge at hips and knees to grip the bar. Keep your back flat and chest up, then drive through your heels to stand up. Lower the bar with control." },
    { name: "Barbell Row", muscle: "back", difficulty: "intermediate", instructions: "Hinge forward at the hips with a flat back. Grip the bar shoulder-width and pull it to your lower chest, squeezing your shoulder blades together. Lower with control." },
    { name: "Dumbbell Row", muscle: "back", difficulty: "beginner", instructions: "Place one knee and hand on a bench for support. Pull the dumbbell up towards your hip, keeping your elbow close to your body. Lower slowly and repeat." },
    { name: "Pull Up", muscle: "back", difficulty: "intermediate", instructions: "Hang from a bar with palms facing away, hands shoulder-width apart. Pull yourself up until your chin is above the bar, then lower with control." },
    { name: "Chin Up", muscle: "back", difficulty: "intermediate", instructions: "Hang from a bar with palms facing toward you, hands shoulder-width apart. Pull yourself up until your chin is above the bar, then lower with control." },
    { name: "Lat Pulldown", muscle: "back", difficulty: "beginner", instructions: "Sit at a cable machine and grip the bar wider than shoulder width. Pull the bar down to your upper chest, squeezing your lats. Return slowly to the starting position." },
    { name: "Seated Cable Row", muscle: "back", difficulty: "beginner", instructions: "Sit at a cable row machine with feet on the platform. Pull the handle to your abdomen, squeezing your shoulder blades together. Return slowly to the starting position." },
    { name: "Face Pull", muscle: "back", difficulty: "beginner", instructions: "Set a cable to upper chest height with a rope attachment. Pull the rope toward your face, separating your hands as you pull. Focus on squeezing your rear delts." },
    { name: "T-Bar Row", muscle: "back", difficulty: "intermediate", instructions: "Straddle a T-bar and hinge forward. Pull the bar to your chest while keeping your back flat and elbows close to your body." },

    // SHOULDERS
    { name: "Overhead Press", muscle: "shoulders", difficulty: "intermediate", instructions: "Stand with feet shoulder-width apart. Hold the bar at shoulder level with hands just outside shoulder width. Press the bar overhead until arms are fully extended, then lower with control." },
    { name: "Dumbbell Shoulder Press", muscle: "shoulders", difficulty: "beginner", instructions: "Sit or stand holding dumbbells at shoulder level with palms facing forward. Press overhead until arms are extended, then lower slowly." },
    { name: "Lateral Raise", muscle: "shoulders", difficulty: "beginner", instructions: "Stand holding dumbbells at your sides. Raise your arms out to the sides until they are parallel to the floor, then lower slowly. Keep a slight bend in your elbows." },
    { name: "Front Raise", muscle: "shoulders", difficulty: "beginner", instructions: "Stand holding dumbbells in front of your thighs. Raise one or both arms forward to shoulder height, then lower slowly." },
    { name: "Arnold Press", muscle: "shoulders", difficulty: "intermediate", instructions: "Start with dumbbells at shoulder level, palms facing you. As you press up, rotate your palms to face forward at the top. Reverse the motion as you lower." },
    { name: "Rear Delt Fly", muscle: "shoulders", difficulty: "beginner", instructions: "Hinge forward at the hips. With a slight bend in your elbows, raise the dumbbells out to the sides until they are level with your shoulders, squeezing your rear delts." },
    { name: "Cable Lateral Raise", muscle: "shoulders", difficulty: "beginner", instructions: "Stand beside a cable machine set at the lowest position. Pull the cable out to the side until your arm is parallel to the floor, then lower with control." },

    // LEGS
    { name: "Barbell Squat", muscle: "quadriceps", difficulty: "intermediate", instructions: "Place the bar on your upper back. Stand with feet shoulder-width apart. Squat down by bending your knees and hips until your thighs are parallel to the floor, then drive back up." },
    { name: "Front Squat", muscle: "quadriceps", difficulty: "advanced", instructions: "Hold the bar across your front shoulders with elbows high. Squat down keeping your torso upright, then drive back up through your heels." },
    { name: "Romanian Deadlift", muscle: "hamstrings", difficulty: "intermediate", instructions: "Stand holding a bar at hip level. Hinge at the hips, pushing them back while lowering the bar down your legs. Keep your back flat. Return to standing by driving your hips forward." },
    { name: "Leg Press", muscle: "quadriceps", difficulty: "beginner", instructions: "Sit in the leg press machine with feet shoulder-width on the platform. Lower the weight by bending your knees to 90 degrees, then press back up." },
    { name: "Leg Extension", muscle: "quadriceps", difficulty: "beginner", instructions: "Sit in the leg extension machine. Extend your legs until they are straight, squeezing your quads at the top. Lower slowly." },
    { name: "Leg Curl", muscle: "hamstrings", difficulty: "beginner", instructions: "Lie face down on the leg curl machine. Curl your legs up toward your glutes, squeezing your hamstrings at the top. Lower slowly." },
    { name: "Bulgarian Split Squat", muscle: "quadriceps", difficulty: "intermediate", instructions: "Stand in front of a bench. Place one foot behind you on the bench. Lower your body until your front thigh is parallel to the floor, then drive back up." },
    { name: "Hip Thrust", muscle: "glutes", difficulty: "beginner", instructions: "Sit with your upper back against a bench. Place a barbell across your hips. Drive your hips up until your body forms a straight line from knees to shoulders, squeezing your glutes at the top." },
    { name: "Calf Raise", muscle: "calves", difficulty: "beginner", instructions: "Stand on the edge of a step or platform. Rise up onto your toes as high as possible, then lower your heels below the step level. Repeat." },
    { name: "Hack Squat", muscle: "quadriceps", difficulty: "intermediate", instructions: "Position yourself in the hack squat machine with shoulders under the pads. Lower until thighs are parallel to the platform, then press back up." },
    { name: "Sumo Deadlift", muscle: "quadriceps", difficulty: "intermediate", instructions: "Stand with feet wider than shoulder width and toes pointed out. Grip the bar inside your legs. Keep your chest up and back flat as you drive through your heels to stand up." },

    // ARMS — BICEPS
    { name: "Barbell Curl", muscle: "biceps", difficulty: "beginner", instructions: "Stand holding a barbell with an underhand grip. Curl the bar up toward your shoulders, keeping your elbows at your sides. Lower slowly." },
    { name: "Dumbbell Curl", muscle: "biceps", difficulty: "beginner", instructions: "Stand holding dumbbells at your sides with palms facing forward. Curl one or both dumbbells up toward your shoulders, then lower slowly." },
    { name: "Hammer Curl", muscle: "biceps", difficulty: "beginner", instructions: "Stand holding dumbbells at your sides with palms facing each other. Curl the dumbbells up while keeping the neutral grip throughout the movement." },
    { name: "Preacher Curl", muscle: "biceps", difficulty: "beginner", instructions: "Sit at a preacher bench. Rest your upper arms on the pad and curl the bar or dumbbells up toward your shoulders, then lower slowly." },
    { name: "Cable Curl", muscle: "biceps", difficulty: "beginner", instructions: "Stand facing a cable machine set at the lowest position. Curl the bar or rope up toward your shoulders, keeping your elbows at your sides." },
    { name: "Incline Dumbbell Curl", muscle: "biceps", difficulty: "beginner", instructions: "Sit on an incline bench holding dumbbells. Let your arms hang straight down, then curl the dumbbells up. The incline increases the stretch on the biceps." },

    // ARMS — TRICEPS
    { name: "Tricep Pushdown", muscle: "triceps", difficulty: "beginner", instructions: "Stand at a cable machine with a bar or rope attachment at chest height. Push the weight down until your arms are fully extended, keeping your elbows at your sides. Return slowly." },
    { name: "Skull Crusher", muscle: "triceps", difficulty: "intermediate", instructions: "Lie on a bench holding a bar or dumbbells above your chest. Bend your elbows to lower the weight toward your forehead, then extend back up." },
    { name: "Tricep Dip", muscle: "triceps", difficulty: "beginner", instructions: "Grip parallel bars with arms extended. Lower your body by bending your elbows, keeping them close to your body. Press back up to the starting position." },
    { name: "Close Grip Bench Press", muscle: "triceps", difficulty: "intermediate", instructions: "Lie on a bench and grip the bar with hands shoulder-width apart. Lower the bar to your chest, keeping your elbows close to your body, then press back up." },
    { name: "Overhead Tricep Extension", muscle: "triceps", difficulty: "beginner", instructions: "Hold a dumbbell or bar overhead with arms extended. Bend your elbows to lower the weight behind your head, then extend back up." },
    { name: "Cable Overhead Tricep Extension", muscle: "triceps", difficulty: "beginner", instructions: "Face away from a cable machine set high. Hold the rope overhead and extend your arms forward, keeping your elbows stationary." },

    // CORE
    { name: "Plank", muscle: "abdominals", difficulty: "beginner", instructions: "Hold a push-up position with your weight on your forearms. Keep your body in a straight line from head to heels. Breathe steadily and hold." },
    { name: "Crunch", muscle: "abdominals", difficulty: "beginner", instructions: "Lie on your back with knees bent. Curl your upper body toward your knees, contracting your abs. Lower slowly and repeat." },
    { name: "Leg Raise", muscle: "abdominals", difficulty: "beginner", instructions: "Lie on your back with legs straight. Raise your legs to 90 degrees, then lower them slowly without letting them touch the floor." },
    { name: "Cable Crunch", muscle: "abdominals", difficulty: "beginner", instructions: "Kneel at a cable machine with a rope attachment. Hold the rope at your head and crunch down, bringing your elbows toward your knees." },
    { name: "Ab Wheel Rollout", muscle: "abdominals", difficulty: "intermediate", instructions: "Kneel on the floor holding an ab wheel. Roll forward as far as you can while keeping your core tight, then roll back to the starting position." },
    { name: "Russian Twist", muscle: "abdominals", difficulty: "beginner", instructions: "Sit on the floor with knees bent and feet raised. Hold a weight and rotate your torso from side to side." },

    // JEFF NIPPARD PROGRAM EXERCISES
    { name: "Assisted Pull-Up", muscle: "back", difficulty: "beginner", instructions: "Slow 2-3 second negative. Feel your lats pulling apart on the way down. Slight 0.5-1 second pause at the bottom, then lift your chest up and drive your elbows down as you lift yourself up. Don't be afraid to use assistance. Keep the form tight and controlled." },
    { name: "Bayesian Cable Curl", muscle: "biceps", difficulty: "intermediate", instructions: "If you have a left-right bicep size imbalance, do these 1 arm at a time, starting with the weaker arm. Take the weaker arm to an RPE of 9-10, then match the reps with the other arm. If no imbalance, do both arms at the same time." },
    { name: "Bent-Over Cable Pec Flye", muscle: "chest", difficulty: "intermediate", instructions: "Lean forward until your torso is parallel with the floor, flye straight out and down toward the floor. Stretch and squeeze the pecs." },
    { name: "Bottom Two Thirds Constant Tension Preacher Curl", muscle: "biceps", difficulty: "intermediate", instructions: "Stay in the bottom 2/3 of the curl. Don't squeeze all the way to the top. Keep your triceps firmly pinned against the pad. No pausing at top or bottom — constant tension on the biceps." },
    { name: "Cable Crunch", muscle: "abdominals", difficulty: "beginner", instructions: "Round your lower back as you crunch. Maintain a mind-muscle connection with your 6-pack." },
    { name: "Cable Paused Shrug-In", muscle: "traps", difficulty: "beginner", instructions: "Shrug up and in, thinking about shrugging up to your ears. 1-2 second pause in the squeeze at the top, then another 1-2 second pause in the stretch at the bottom." },
    { name: "Cable Reverse Flye Mechanical Dropset", muscle: "shoulders", difficulty: "advanced", instructions: "Take 3 big steps back from the cable machine and do your first 5 reps. Immediately take 1 step forward and do another 4 reps. Then take another step forward and do at least 3 more or until RPE 9-10." },
    { name: "Cable Triceps Kickback", muscle: "triceps", difficulty: "beginner", instructions: "Two options: upright or bent over — pick whichever feels more comfortable. The key is that at full squeeze, your shoulder should be positioned back behind your torso." },
    { name: "Chest-Supported Machine Row", muscle: "back", difficulty: "beginner", instructions: "Flare elbows out at roughly 45° and squeeze your shoulder blades together hard at the top of each rep." },
    { name: "Chest-Supported T-Bar Row Plus Kelso Shrug", muscle: "back", difficulty: "intermediate", instructions: "Do 8-10 reps as a normal T-Bar row, driving elbows back at 45° and squeezing shoulder blades together. Without resting, do another 4-6 reps as Kelso Shrugs — squeeze shoulder blades together without rowing back with your arms." },
    { name: "Concentration Cable Curl", muscle: "biceps", difficulty: "intermediate", instructions: "Paired with single-arm overhead triceps extension: do concentration curls on one arm, rest 0.5-1 min, triceps extensions same arm, rest, curls on the other arm, rest, extensions on the other arm, rest, repeat." },
    { name: "Cross-Body Lat Pull-Around", muscle: "back", difficulty: "intermediate", instructions: "Try to keep the cable and your wrist aligned in a straight line throughout the pull. Feel a nice, deep lat stretch at the top." },
    { name: "Cuffed Behind-The-Back Lateral Raise", muscle: "shoulders", difficulty: "intermediate", instructions: "Raise the cables up and out in a Y motion. Really try to connect with the middle delt fibers as you sweep the weight up and out." },
    { name: "DB Calf Jumps", muscle: "calves", difficulty: "intermediate", instructions: "Hold a dumbbell and perform a jumping motion without actually leaving the floor, using a slight knee bend but mostly relying on your calves and ankles to drive the jump. Meant to mimic the jump-rope stimulus with more tension." },
    { name: "Decline Machine Chest Press", muscle: "chest", difficulty: "beginner", instructions: "Feel your pecs stretching apart on the negative. Mind-muscle connection with lower pecs." },
    { name: "Dual-Handle Lat Pulldown", muscle: "back", difficulty: "intermediate", instructions: "Lean back by 15° and drive your elbows down as you squeeze your shoulder blades together. Should feel like a mix of lats and mid-traps." },
    { name: "Hack Squat", muscle: "quadriceps", difficulty: "intermediate", instructions: "Reverse pyramid. Warm up to your first working set for 4 reps — this is your heaviest set. Set 2, drop the weight 10-15% and do 6 reps. Set 3, drop another 10-15% and do 8 reps." },
    { name: "Hammer Curl", muscle: "biceps", difficulty: "beginner", instructions: "Squeeze the dumbbell hard in the middle of the handle as you curl. Liquid chalk prevents grip slipping, keeping your hand centered rather than resting against the dumbbell head." },
    { name: "Hammer Preacher Curl", muscle: "biceps", difficulty: "intermediate", instructions: "Targets the brachialis and forearms hard. Squeeze the dumbbell hard in the middle of the handle and curl about 3/4 of the way up — stay in the bottom 3/4 of the curl." },
    { name: "Lat-Focused Cable Row", muscle: "back", difficulty: "intermediate", instructions: "Keep your torso locked in a fixed position — don't lean forward on the negative. Drive your elbows down and back to engage the lats. Keep elbows tucked in to your sides." },
    { name: "Leg Extension", muscle: "quadriceps", difficulty: "beginner", instructions: "Set the seat back as far as it will go while still comfortable. Grab the handles as hard as you can to pull your butt down into the seat. 2-3 second negative. Feel your quads pulling apart on the negative." },
    { name: "Leg Press", muscle: "quadriceps", difficulty: "beginner", instructions: "Feet lower on the platform for more quad focus. Get as deep as you can without excessive back rounding. Control the negative and do a slight pause at the bottom. Try to add a little weight each week at the same rep count." },
    { name: "Leg Press Calf Press", muscle: "calves", difficulty: "beginner", instructions: "1-2 second pause at the bottom of each rep. Instead of just going up onto your toes, think about rolling your ankle back and forth on the balls of your feet." },
    { name: "Low Incline DB Press", muscle: "chest", difficulty: "intermediate", instructions: "Set the bench at a 15° incline. Slight elbow tuck on the negative, then flare as you push. Smooth reps, no pausing at top or bottom — constant tension on the pecs." },
    { name: "Low Incline Smith Machine Press", muscle: "chest", difficulty: "intermediate", instructions: "Set the bench at a 15° incline. 1 second pause on the chest each rep while maintaining tension on the pecs." },
    { name: "Lying Leg Curl", muscle: "hamstrings", difficulty: "beginner", instructions: "Set the machine so you get the biggest stretch possible at the bottom. Prevent your butt from popping up as you curl. Once you can't reach full squeeze, continue with partial reps on the last set." },
    { name: "Lying Paused Rope Face Pull", muscle: "shoulders", difficulty: "beginner", instructions: "Pause for 1-2 seconds in the squeeze of each rep. Contract the rear delts hard." },
    { name: "Machine Hip Abduction", muscle: "glutes", difficulty: "beginner", instructions: "If possible, use pads to increase the range of motion on the machine. Lean forward and grab onto the machine rails to stretch the glutes further." },
    { name: "Machine Hip Adduction", muscle: "adductors", difficulty: "beginner", instructions: "Mind-muscle connection with your inner thighs. Great for adding thigh mass from the front. Push them hard." },
    { name: "Machine Shoulder Press", muscle: "shoulders", difficulty: "beginner", instructions: "Ensure that your elbows break at least 90°. Mind-muscle connection with your delts. Smooth, controlled reps." },
    { name: "Medicine Ball Russian Twists", muscle: "abdominals", difficulty: "intermediate", instructions: "Keep the ball held out far from your body on the sides and control the reps — don't rush through them to get the set done." },
    { name: "Neutral-Grip Lat Pulldown", muscle: "back", difficulty: "beginner", instructions: "Do these with the handle more out in front of you, like a cross between a pullover and a pulldown. Focus on feeling your lats working more than the weight you're using." },
    { name: "Overhead Cable Triceps Extension", muscle: "triceps", difficulty: "intermediate", instructions: "Feel a nasty stretch on the triceps throughout the entire negative. Pause for 1 second in the stretch part of each rep." },
    { name: "Paused Assisted Dip", muscle: "chest", difficulty: "beginner", instructions: "Slow 2-3 second negative. 1-2 second pause at the bottom. Explode with control on the way up. Go as deep as your shoulders comfortably allow, at least breaking a 90° elbow angle." },
    { name: "Paused Barbell RDL", muscle: "hamstrings", difficulty: "intermediate", instructions: "RPE is intentionally low because these cause a lot of muscle damage — don't be tempted to go too heavy. 1 second pause at the bottom of each rep. Stop about 75% of the way to full lockout to keep tension on the hamstrings." },
    { name: "Pec Deck with Integrated Partials", muscle: "chest", difficulty: "intermediate", instructions: "Set up for maximum stretch. On all sets, alternate full-ROM and half-ROM reps — 1 full, 1 half in the stretched bottom half, 1 full, 1 half. Repeat until you've hit the target reps at RPE 9-10." },
    { name: "Rear Delt 45 Degree Cable Flye", muscle: "shoulders", difficulty: "intermediate", instructions: "Pull with one arm at a time, bracing with your non-working hand against the machine. Try to align your arm and the cable in a straight line at the bottom of the flye." },
    { name: "Reverse Pec Deck with Integrated Partials", muscle: "shoulders", difficulty: "intermediate", instructions: "Sweep the weight out instead of pulling it back. Mind-muscle connection with rear delts. On all sets, alternate full-ROM and half-ROM reps until target reps and RPE 9-10." },
    { name: "Roman Chair Leg Raise", muscle: "abdominals", difficulty: "intermediate", instructions: "Allow your lower back to round as you curl your legs up. Go until you hit RPE 9-10 with controlled form." },
    { name: "Seated DB Shoulder Press", muscle: "shoulders", difficulty: "beginner", instructions: "Slightly rotate the dumbbells in on the negative and flare your elbows out as you push." },
    { name: "Seated Leg Curl", muscle: "hamstrings", difficulty: "beginner", instructions: "Lean forward over the machine to get a maximum stretch in your hamstrings." },
    { name: "Single-Arm Overhead Cable Triceps Extension", muscle: "triceps", difficulty: "intermediate", instructions: "Paired with concentration cable curls — alternate arms with 0.5-1 min rest between each mini-set." },
    { name: "Slow Eccentric Bayesian Curl", muscle: "biceps", difficulty: "intermediate", instructions: "Use a 3-4 second negative and a slight pause at the bottom of each rep to emphasize stretching your biceps." },
    { name: "Slow Eccentric DB RDL", muscle: "hamstrings", difficulty: "intermediate", instructions: "Lower the dumbbells with a 3-4 second negative. For more glutes, squeeze hard at the top at full lockout. For more hamstrings, only go to 3/4 of full lockout and maintain constant tension." },
    { name: "Slow Eccentric EZ-Bar Skull Crusher", muscle: "triceps", difficulty: "intermediate", instructions: "Use a 3-4 second negative. Arc the EZ-bar slightly back behind your head. When you extend, keep the bar behind your eye line. Use the inside grip and allow the elbows to flare to a comfortable degree." },
    { name: "Smith Machine Reverse Lunge", muscle: "quadriceps", difficulty: "intermediate", instructions: "Set one leg back on the negative and then drive the weight up using your front leg. Try to minimize assistance from your back leg." },
    { name: "Smith Machine Squat", muscle: "quadriceps", difficulty: "intermediate", instructions: "Reverse pyramid. Warm up to your first working set for 4 reps — heaviest set. Set 2, drop 10-15% for 6 reps. Set 3, drop another 10-15% for 8 reps." },
    { name: "Standing Calf Raise", muscle: "calves", difficulty: "beginner", instructions: "1-2 second pause at the bottom of each rep. Instead of just going up onto your toes, think about rolling your ankle back and forth on the balls of your feet." },
    { name: "Super ROM DB Lateral Raise", muscle: "shoulders", difficulty: "intermediate", instructions: "Perform lateral raises as normal but go until your hands are overhead. As you break parallel you'll use more upper traps. If you feel shoulder pain going all the way up, try pointing your thumb up, or just stop at parallel." },
    { name: "Super ROM Overhand Cable Row", muscle: "back", difficulty: "intermediate", instructions: "Set up a wide-grip pulldown bar on a seated cable row. Using a double overhand grip, row while leaning forward on the negative, then extend your torso upright as you finish the row." },
    { name: "Triceps Diverging Pressdown", muscle: "triceps", difficulty: "intermediate", instructions: "Use two long ropes or one long rope. Lean slightly forward, flare your elbows slightly out, keep your arms back in line with your torso. Then press down, getting a full, big squeeze at the bottom." },
    { name: "Triceps Pressdown Bar", muscle: "triceps", difficulty: "beginner", instructions: "Meant to be fairly heavy, which is why it's a bar instead of a rope. Aim to add weight week to week at the set rep target. Keep the form tight as you overload the triceps." },
];

export function searchLocalExercises(query) {
    const q = query.toLowerCase().trim();
    return exerciseDatabase.filter(ex =>
        ex.name.toLowerCase().includes(q) ||
        ex.muscle.toLowerCase().includes(q)
    );
}